export const ErrorMessages = {
  PRODUCT_NOT_FOUND: "Product not found",
  CART_NOT_FOUND: "Cart not found",
  USER_NOT_FOUND: "User not found",
  ORDER_NOT_FOUND: "Order not found",
  NOT_FOUND: "Not found",
  BAD_REQUEST: "Bad request",
  INTERNAL_SERVER_ERROR: "Internal server error",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  CONFLICT: "Conflict",
  UNPROCESSABLE_ENTITY: "Unprocessable entity",
  MISSING_FIELDS: "Missing fields",
  TICKET_NOT_FOUND: "Ticket not found",
  INVALID_CREDENTIALS: "Invalid credentials",
};
